### ISSUE TITLE
Compatibility with python 2.7.*

### ISSUE THREAD

**Issue by DarkstaIkers** [FichteFoll/hexchat-addons#2]
I'm getting this error (http://i.imgur.com/rTyHKrB.png) on python 2.7.13

And yes, I'm aware the script requires python 3, so if it's not ask too much, could you please make the script compatible with python 2.7.13?

**Comment by DarkstaIkers** [comment]
Well, never mind.

**Comment by FichteFoll** [comment]
Did you manage to get python 2.7 compatibility yourself?

**Comment by DarkstaIkers** [comment]
Somehow I did manage to install python 3.5 and it's working like a charm now.

Thanks for that awesome script :)

**Comment by FichteFoll** [comment]
I see, that's even better. Everyone should be using 3.4+. 😄 Glad you like it, too. I'll likely add property expansion for UNIX soon now that I use it primarily and have a testing environment.

That aside, unless there is demand for scripts working in 2.7, I'm not going to make them compatible because 3 is just better than 2. It wouldn't be that hard to use the Python-2-and-3 subset for that script, tbh, but maintenance increases because I don't have a single hexchat instance working with 2 for testing.
